mdb1:
  image: mongo
  ports:
    - 27017:27017
  volumes:
    - ~/docker/mongodb:/var/lib/mongodb
  restart: always
  
ide:
  image: jborozdina/gloseval-dev
  environment: 
    - DISPLAY=
  ports:
    - 9876:9876
  volumes:
    - ~/docker/intellij:/home/dev/share
